
all:
	$(CC) $(CLFL_BASE) $(CLFL_CPU) $(CLFL_OX) $(CLFL_ADDON) /c *.c /Fo:$(PROJECT_OBJECT_PATH)/dropper/
	$(CC) $(CLFL_BASE) $(CLFL_CPU) $(CLFL_OX) $(CLFL_ADDON) /c crypto/*.c /Fo:$(PROJECT_OBJECT_PATH)/dropper/crypto/
	$(CC) $(CLFL_BASE) $(CLFL_CPU) $(CLFL_OX) $(CLFL_ADDON) /c ntapi/*.c /Fo:$(PROJECT_OBJECT_PATH)/dropper/ntapi/
